# Generated by Django 2.1.2 on 2018-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacion',
            name='memoria',
        ),
        migrations.AddField(
            model_name='proceso',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='simulacion_pid',
            field=models.IntegerField(default=0, verbose_name='PID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proceso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tiempo_recursos',
            field=models.TextField(verbose_name='Tiempo de recursos'),
        ),
    ]
